In [ ]:
import pandas as pd

caminho = '/content/drive/MyDrive/Ciência de Dados/Pessoas.xlsx'
arquivo = pd.read_excel(caminho)

print("Informações do DataFrame inicial:")
arquivo.info()

Informações do DataFrame inicial:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nome    20 non-null     object
 1   Idade   20 non-null     int64
 2   Peso    20 non-null     float64
 3   Altura  20 non-null     float64
dtypes: float64(2), int64(1), object(1)
memory usage: 772.0+ bytes

In [ ]:
# Qual a media de idade?
media_idade = arquivo['Idade'].mean()
print(f"Média de idade: {media_idade:.2f} anos")

# Qual o menor peso?
menor_peso = arquivo['Peso'].min()
print(f"Menor peso: {menor_peso:.2f} kg")

# Qual a maior altura?
maior_altura = arquivo['Altura'].max()
print(f"Maior altura: {maior_altura:.2f} m")

# Criar a coluna IMC
arquivo['IMC'] = arquivo['Peso'] / (arquivo['Altura'] ** 2)

# Grupo IMC dominante
def classificar_imc(imc):
    if imc < 18.5:
        return 'Abaixo do peso'
    elif 18.5 <= imc <= 24.9:
        return 'Peso normal'
    elif 25.0 <= imc <= 29.9:
        return 'Sobrepeso'
    else:
        return 'Obesidade'

arquivo['Grupo_IMC'] = arquivo['IMC'].apply(classificar_imc)

grupo_dominante = arquivo['Grupo_IMC'].mode()[0]
print(f"Grupo IMC dominante: {grupo_dominante}")

Média de idade: 31.45 anos
Menor peso: 54.00 kg
Maior altura: 1.85 m
Grupo IMC dominante: Peso normal
--------------------------------------------------

In [ ]:
def contar_vogais(nome):
    vogais = "aeiouAEIOUáéíóúÁÉÍÓÚãõÃÕâêîôûÂÊÎÔÛ"
    return sum(1 for letra in str(nome) if letra in vogais)

arquivo['Num_Vogais_Nome'] = arquivo['Nome'].apply(contar_vogais)

arquivo['Relacao_Idade_IMC'] = arquivo['Idade'] / arquivo['IMC']

display(arquivo)

Visualização final da tabela:

,Nome,Idade,Peso,Altura,IMC,Grupo_IMC,Num_Vogais_Nome,Relacao_Idade_IMC
0,Ana Souza,28,62.5,1.65,22.956841,Peso normal,5,1.219680
1,Bernardo Lima,32,78.0,1.76,25.180785,Sobrepeso,5,1.270810
2,Carlos Silva,45,85.2,1.80,26.296296,Sobrepeso,4,1.711268
3,Daniela Costa,22,55.4,1.60,21.640625,Peso normal,6,1.016606
4,Eduardo Santos,34,90.1,1.85,26.325785,Sobrepeso,6,1.291509
5,Fernanda Oliveira,29,68.0,1.70,23.529412,Peso normal,8,1.232500
6,Gabriel Rocha,25,72.3,1.75,23.608163,Peso normal,5,1.058956
7,Helena Mendes,40,64.8,1.62,24.691358,Peso normal,5,1.620000
8,Igor Fernandes,38,88.5,1.78,27.932079,Sobrepeso,5,1.360443
9,Juliana Pereira,27,59.0,1.58,23.634033,Peso normal,8,1.142420
10,Lucas Almeida,31,76.4,1.82,23.064847,Peso normal,6,1.344037
11,Mariana Ribeiro,26,61.2,1.68,21.683673,Peso normal,8,1.199059
12,Nicolas Martins,35,81.0,1.77,25.854639,Sobrepeso,5,1.353722
13,Olívia Castro,24,58.5,1.64,21.750446,Peso normal,6,1.103426
14,Pedro Gomes,42,92.0,1.81,28.082171,Sobrepeso,4,1.495611
15,Rafael Carvalho,30,74.5,1.74,24.606949,Peso normal,6,1.219168
16,Sofia Barros,23,54.0,1.61,20.832530,Peso normal,5,1.104043
17,Tiago Moraes,37,83.7,1.79,26.122780,Sobrepeso,6,1.416388
18,Valentina Dias,33,66.2,1.67,23.736957,Peso normal,6,1.390237
19,Vinícius Nunes,28,79.8,1.83,23.828720,Peso normal,6,1.175053

In [ ]:
grupo_dominante = arquivo['Grupo_IMC'].mode()[0]
quantidade = (arquivo['Grupo_IMC'] == grupo_dominante).sum()

print(f"Grupo IMC dominante: {grupo_dominante} (Quantidade: {quantidade})")

Grupo IMC dominante: Peso normal (Quantidade: 13)

In [ ]:
print("Visualização final da tabela:")
display(arquivo)

caminho_salvar = '/content/drive/MyDrive/Ciência de Dados/Pessoas_IMC_Atualizado.xlsx'
arquivo.to_excel(caminho_salvar, index=False)
print(f"DataFrame salvo com sucesso em: {caminho_salvar}")

Visualização final da tabela:

,Nome,Idade,Peso,Altura,IMC,Grupo_IMC,Num_Vogais_Nome,Relacao_Idade_IMC
0,Ana Souza,28,62.5,1.65,22.956841,Peso normal,5,1.219680
1,Bernardo Lima,32,78.0,1.76,25.180785,Sobrepeso,5,1.270810
2,Carlos Silva,45,85.2,1.80,26.296296,Sobrepeso,4,1.711268
3,Daniela Costa,22,55.4,1.60,21.640625,Peso normal,6,1.016606
4,Eduardo Santos,34,90.1,1.85,26.325785,Sobrepeso,6,1.291509
5,Fernanda Oliveira,29,68.0,1.70,23.529412,Peso normal,8,1.232500
6,Gabriel Rocha,25,72.3,1.75,23.608163,Peso normal,5,1.058956
7,Helena Mendes,40,64.8,1.62,24.691358,Peso normal,5,1.620000
8,Igor Fernandes,38,88.5,1.78,27.932079,Sobrepeso,5,1.360443
9,Juliana Pereira,27,59.0,1.58,23.634033,Peso normal,8,1.142420
10,Lucas Almeida,31,76.4,1.82,23.064847,Peso normal,6,1.344037
11,Mariana Ribeiro,26,61.2,1.68,21.683673,Peso normal,8,1.199059
12,Nicolas Martins,35,81.0,1.77,25.854639,Sobrepeso,5,1.353722
13,Olívia Castro,24,58.5,1.64,21.750446,Peso normal,6,1.103426
14,Pedro Gomes,42,92.0,1.81,28.082171,Sobrepeso,4,1.495611
15,Rafael Carvalho,30,74.5,1.74,24.606949,Peso normal,6,1.219168
16,Sofia Barros,23,54.0,1.61,20.832530,Peso normal,5,1.104043
17,Tiago Moraes,37,83.7,1.79,26.122780,Sobrepeso,6,1.416388
18,Valentina Dias,33,66.2,1.67,23.736957,Peso normal,6,1.390237
19,Vinícius Nunes,28,79.8,1.83,23.828720,Peso normal,6,1.175053

DataFrame salvo com sucesso em: /content/drive/MyDrive/Ciência de Dados/Pessoas_IMC_Atualizado.xlsx