In [ ]:
import pandas as pd

caminho = '/content/drive/MyDrive/Ciência de Dados/Dados/Vendas.csv'
arquivo = pd.read_csv(caminho)

In [ ]:
print(arquivo.tail(3))
print(arquivo.columns)
print(arquivo.dtypes)

Index(['ID_Venda', 'Produto', 'Faturamento', 'Quantidade', 'Data'], dtype='object')

In [ ]:
arquivo.loc[arquivo['Faturamento'] > 500]

arquivo['Produto'].value_counts()

arquivo.iloc[4:8, [1, 2]]

Produto
Teclado    3
Mouse      3
Monitor    3
Cadeira    1
Name: count, dtype: int64

In [ ]:
# arquivo['Faturamento'] = arquivo['Faturamento'].fillna(0)

# arquivo['Data'] = pd.to_datetime(arquivo['Data'])

# arquivo['Ticket_Medio'] = arquivo['Faturamento'] / arquivo['Quantidade']

Index(['ID_Venda', 'Produto', 'Faturamento', 'Quantidade', 'Data',
       'Ticket_Medio'],
      dtype='object')

In [ ]:
# arquivo.groupby('Data')['Faturamento'].sum()

# arquivo.groupby('Produto')['Quantidade'].mean()

res = arquivo.groupby('Produto')['Faturamento'].sum()
res.sort_values(ascending=False)

Produto
Monitor    3600.0
Cadeira     850.0
Teclado     451.5
Mouse       160.0
Name: Faturamento, dtype: float64

In [ ]:
arquivo.tail()
arquivo.head()

   ID_Venda  Produto  Faturamento  Quantidade       Data  Ticket_Medio
0       101  Teclado        150.5           2 2024-01-01     75.250000
1       102    Mouse         80.0           5 2024-01-01     16.000000
2       103  Monitor       1200.0           1 2024-01-02   1200.000000
3       104    Mouse         80.0           3 2024-01-02     26.666667
4       105  Teclado        150.5           2 2024-01-03     75.250000

In [ ]:
import pandas as pd

caminho = '/content/drive/MyDrive/Ciência de Dados/Dados/Cidades.xlsx'
arquivo = pd.read_excel(caminho)

In [ ]:
arquivo = arquivo.set_index('Cidade')
porto_alegre_data = arquivo.loc['Porto Alegre']
display(porto_alegre_data)

idh_sp_salvador = arquivo.loc[['São Paulo', 'Salvador'], 'IDH']
display(idh_sp_salvador)

Cidade
São Paulo    0.783
Salvador     0.759
Name: IDH, dtype: float64

In [ ]:
primeira_linha = arquivo.iloc[0]
display(primeira_linha)

UF                  SP
Habitantes    12325232
IDH              0.783
Name: São Paulo, dtype: object

In [ ]:
duas_primeiras_linhas_colunas = arquivo.iloc[0:1, 0:1]
display(duas_primeiras_linhas_colunas)

           UF
Cidade
São Paulo  SP

In [ ]:
idh_belo_horizonte = arquivo.at['Belo Horizonte', 'IDH']
display(f"valor: {idh_belo_horizonte}")

'valor: 0.81'

In [ ]:
valor = arquivo.iat[-1, -1]
display(f"Valor: {valor}")

'Valor: 0.759'

In [ ]:
cidades_filtradas = arquivo.loc[arquivo['Habitantes'] > 2000000, ['UF', 'IDH']].reset_index(drop=True)
display(cidades_filtradas)

   UF    IDH
0  SP  0.783
1  RJ  0.761
2  MG  0.810
3  BA  0.759

In [ ]:
habitantes_por_uf = arquivo.groupby('UF')['Habitantes'].sum()
display(habitantes_por_uf)

UF
BA     2886698
MG     2521564
RJ     6747815
RS     1488252
SP    12325232
Name: Habitantes, dtype: int64

In [ ]:
if 'Cidade' in arquivo.index.names:
    arquivo = arquivo.reset_index()

new_cities_df = pd.DataFrame([
    {'Cidade': 'Guaruja do Sul', 'UF': 'SC', 'Habitantes': 5000, 'IDH': 0.700},
    {'Cidade': 'Caçapava do Sul', 'UF': 'RS', 'Habitantes': 30000, 'IDH': 0.720},
    {'Cidade': 'São Sepe', 'UF': 'RS', 'Habitantes': 25000, 'IDH': 0.500}
])

arquivo = pd.concat([arquivo, new_cities_df], ignore_index=True)

arquivo['Categoria'] = arquivo['Habitantes'].apply(lambda x: 'Metrópole' if x > 1000000 else 'Interior')
display(arquivo)

            Cidade  UF  Habitantes    IDH  Categoria
0        São Paulo  SP    12325232  0.783  Metrópole
1   Rio de Janeiro  RJ     6747815  0.761  Metrópole
2   Belo Horizonte  MG     2521564  0.810  Metrópole
3     Porto Alegre  RS     1488252  0.805  Metrópole
4         Salvador  BA     2886698  0.759  Metrópole
5   Guaruja do Sul  SC        5000  0.700   Interior
6  Caçapava do Sul  RS       30000  0.720   Interior
7         São Sepe  RS       25000  0.500   Interior

In [ ]:
idh_por_categoria = arquivo.groupby('Categoria')['IDH'].agg(['min', 'mean', 'max'])
display(idh_por_categoria)

             min    mean   max
Categoria
Interior   0.500  0.6400  0.72
Metrópole  0.759  0.7836  0.81

In [ ]:
contagem_distribuida = arquivo.groupby(['UF', 'Categoria']).size()
display(contagem_distribuida)

UF  Categoria
BA  Metrópole    1
MG  Metrópole    1
RJ  Metrópole    1
RS  Interior     2
    Metrópole    1
SC  Interior     1
SP  Metrópole    1
dtype: int64