In [ ]:
import pandas as pd

caminho = '/content/drive/MyDrive/Ciência de Dados/Notas.xlsx'
arquivo = pd.read_excel(caminho)

# arquivo.info()
# arquivo.describe()
print(arquivo)

        Nome  Nota1  Nota2  Nota3  NrFaltas
0       João    7.0      4      5         5
1      Maria    8.0      7      7         3
2       José    6.0      8      6         3
3    Joaquim    NaN      6      7         8
4  Alcebides    9.0      9      9         4

In [ ]:
arquivo = arquivo.fillna(0)

arquivo['Nota2'] = arquivo ['Nota2'].astype(float)
arquivo['Nota3'] = arquivo ['Nota3'].astype(float)
arquivo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nome      5 non-null      object
 1   Nota1     5 non-null      float64
 2   Nota2     5 non-null      float64
 3   Nota3     5 non-null      float64
 4   NrFaltas  5 non-null      int64
dtypes: float64(3), int64(1), object(1)
memory usage: 332.0+ bytes

In [ ]:
# arquivo.info()
# arquivo.describe()
arquivo.iloc[0]

Nome        João
Nota1        7.0
Nota2        4.0
Nota3        5.0
NrFaltas       5
Name: 0, dtype: object

In [ ]:
print(len(arquivo))
tamanho = len(arquivo)

for indice in range(tamanho):
  print(arquivo.iloc[indice])

5
Nome        João
Nota1        7.0
Nota2        4.0
Nota3        5.0
NrFaltas       5
Name: 0, dtype: object
Nome        Maria
Nota1         8.0
Nota2         7.0
Nota3         7.0
NrFaltas        3
Name: 1, dtype: object
Nome        José
Nota1        6.0
Nota2        8.0
Nota3        6.0
NrFaltas       3
Name: 2, dtype: object
Nome        Joaquim
Nota1           0.0
Nota2           6.0
Nota3           7.0
NrFaltas          8
Name: 3, dtype: object
Nome        Alcebides
Nota1             9.0
Nota2             9.0
Nota3             9.0
NrFaltas            4
Name: 4, dtype: object

In [ ]:
#Média de cada nota

media_notas = arquivo[['Nota1', 'Nota2', 'Nota3']].mean()

print("Médias das Notas:")
for nota, media in media_notas.items():
    print(f"{nota}: {media:.2f}")

Médias das Notas:
Nota1: 6.00
Nota2: 6.80
Nota3: 6.80

In [ ]:
#Média de cada aluno

arquivo['Media_Notas'] = arquivo[['Nota1', 'Nota2', 'Nota3']].mean(axis=1)
nota_minima_aprovacao = 6.0
arquivo['Situação'] = arquivo['Media_Notas'].apply(lambda x: 'aprovado' if x >= nota_minima_aprovacao else 'reprovado')
display(arquivo)

        Nome  Nota1  Nota2  Nota3  NrFaltas  Media_Notas   Situação
0       João    7.0    4.0    5.0         5     5.333333  reprovado
1      Maria    8.0    7.0    7.0         3     7.333333   aprovado
2       José    6.0    8.0    6.0         3     6.666667   aprovado
3    Joaquim    0.0    6.0    7.0         8     4.333333  reprovado
4  Alcebides    9.0    9.0    9.0         4     9.000000   aprovado

In [ ]:
caminho_salvar = '/content/drive/MyDrive/Ciência de Dados/Notas_Atualizadas.xlsx'
arquivo.to_excel(caminho_salvar, index=False)
print(f"DataFrame salvo com sucesso em: {caminho_salvar}")

DataFrame salvo com sucesso em: /content/drive/MyDrive/Ciência de Dados/Notas_Atualizadas.xlsx